list_ex = [
    ".java",  # <-- java
    ".jsp",
    ".js",  # <-- JavaScript
    "._js",
    ".bones",
    ".es",
    ".es6",
    ".frag",
    ".gs",
    ".jake",
    ".jsb",
    ".jscad",
    ".jsfl",
    ".jsm",
    ".jss",
    ".njs",
    ".pac",
    ".sjs",
    ".ssjs",
    ".sublime-build",
    ".sublime-commands",
    ".sublime-completions",
    ".sublime-keymap",
    ".sublime-macro",
    ".sublime-menu",
    ".sublime-mousemap",
    ".sublime-project",
    ".sublime-settings",
    ".sublime-theme",
    ".sublime-workspace",
    ".sublime_metrics",
    ".sublime_session",
    ".xsjs",
    ".xsjslib",
    ".css",  # <--css
    ".c",  # <--C
    ".cats",
    ".h",
    ".idc",
    ".w",
    ".cs",  # <--C#
    ".cake",
    ".cshtml",
    ".csx",
    ".cpp",  # <--C++
    ".c++",
    ".cc",
    ".cp",
    ".cxx",
    ".h",
    ".h++",
    ".hh",
    ".hpp",
    ".hxx",
    ".inc",
    ".inl",
    ".ipp",
    ".tcc",
    ".tpp",
    ".php",  # <--PHP
    ".aw",
    ".ctp",
    ".fcgi",
    ".inc",
    ".php3",
    ".php4",
    ".php5",
    ".phps",
    ".phpt",
    ".go",  # <--Go
    ".rs",  # <--Rust
    ".rs.in"]
